### ISSUE TITLE
Mention bevy_cosmic_edit default feature in README

### ISSUE THREAD

**Issue by rudderbucky** [databasedav/haalka#3]
Since `bevy_cosmic_edit` auto-panics on multiple cameras unless the `multicam` feature is enabled, there's a bit of friction onboarding a project that uses many cameras to haalka. It would be best IMO to mention this in the README as a prerequisite to help expedite onboarding.

**Comment by databasedav** [comment]
o that's unfortunate, so right now, one would have to add a dependency for `bevy_cosmic_edit` and add that feature, which is way too much

i guess my only choice is to add a `multicam` feature to `haalka` which activates `bevy_cosmic_edit`'s :thinking:

**Comment by rudderbucky** [comment]
Not necessarily, since `bevy_cosmic_edit` is optional I was able to disable default features and get away without specifying `multicam` at all, since I don't use `bevy_cosmic_edit`. It's probably enough to specify this feature in the README as one that can be disabled.

**Comment by databasedav** [comment]
https://github.com/databasedav/haalka/pull/4
